baseurl: "https://tonytwang.net/"
languageCode: "en-us"
title: "t. TW"

# See https://gohugo.io/getting-started/configuration-markup/ for details
markup:
  goldmark:
    renderer:
      unsafe: true

staticDir:
  - "static"
  - "favicons"  # favicon files should be in root of site
